# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\AAA个人项目\python_vscode\ImageProcess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageProcess(object):
    def setupUi(self, ImageProcess):
        ImageProcess.setObjectName("ImageProcess")
        ImageProcess.resize(1145, 902)
        self.centralwidget = QtWidgets.QWidget(ImageProcess)
        self.centralwidget.setObjectName("centralwidget")
        self.Btn_select_pic = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_select_pic.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.Btn_select_pic.setObjectName("Btn_select_pic")
        self.pic_src = QtWidgets.QLabel(self.centralwidget)
        self.pic_src.setGeometry(QtCore.QRect(20, 170, 511, 541))
        self.pic_src.setStyleSheet("border: 1px solid black;")
        self.pic_src.setText("")
        self.pic_src.setObjectName("pic_src")
        self.pic_dst = QtWidgets.QLabel(self.centralwidget)
        self.pic_dst.setGeometry(QtCore.QRect(590, 170, 511, 541))
        self.pic_dst.setStyleSheet("border: 1px solid black;")
        self.pic_dst.setText("")
        self.pic_dst.setObjectName("pic_dst")
        self.Btn_Mean_Filter = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Mean_Filter.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.Btn_Mean_Filter.setObjectName("Btn_Mean_Filter")
        self.Btn_Gaussian_Filter = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Gaussian_Filter.setGeometry(QtCore.QRect(20, 70, 75, 23))
        self.Btn_Gaussian_Filter.setObjectName("Btn_Gaussian_Filter")
        ImageProcess.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageProcess)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 23))
        self.menubar.setObjectName("menubar")
        ImageProcess.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageProcess)
        self.statusbar.setObjectName("statusbar")
        ImageProcess.setStatusBar(self.statusbar)

        self.retranslateUi(ImageProcess)
        self.Btn_select_pic.clicked.connect(ImageProcess.On_Btn_select_pic_clicked) # type: ignore
        self.Btn_Mean_Filter.clicked.connect(ImageProcess.On_Btn_select_pic_clicked) # type: ignore
        self.Btn_Gaussian_Filter.clicked.connect(ImageProcess.On_Btn_Gaussian_Filter_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageProcess)

    def retranslateUi(self, ImageProcess):
        _translate = QtCore.QCoreApplication.translate
        ImageProcess.setWindowTitle(_translate("ImageProcess", "图像处理系统"))
        self.Btn_select_pic.setText(_translate("ImageProcess", "选择图片"))
        self.Btn_Mean_Filter.setText(_translate("ImageProcess", "均值滤波"))
        self.Btn_Gaussian_Filter.setText(_translate("ImageProcess", "高斯滤波"))
