
import vtk

#vtk基本演示
# sphere = vtkSphereSource()
# sphere.SetRadius(10.0)
# mapper = vtkPolyDataMapper()
# mapper.SetInputConnection(sphere.GetOutputPort())
# actor = vtkActor()
# actor.SetMapper(mapper)
# renderer = vtkRenderer()
# renderer.AddActor(actor)
# renderer.SetBackground(0.1, 0.2, 0.4)
# window = vtkRenderWindow()
# window.AddRenderer(renderer)
# window.SetSize(600, 600)
# interactor = vtkRenderWindowInteractor()
# interactor.SetRenderWindow(window)
# style = vtkInteractorStyleTrackballCamera()
# interactor.SetInteractorStyle(style)
# interactor.Initialize()
# window.Render()
# interactor.Start()

#vtk体渲染
reader1 = vtk.vtkDICOMImageReader()
reader1.SetDirectoryName("3.000000-TRI LIVER C--55249")
reader1.Update()
reader = vtk.vtkImageFlip()
reader.SetInputData(reader1.GetOutput())
reader.Update()
dimensions = reader.GetOutput().GetDimensions()
print("dimensions:",dimensions)
volumeMapper = vtk.vtkGPUVolumeRayCastMapper()
volumeMapper.SetInputConnection(reader.GetOutputPort())
volume = vtk.vtkVolume()
volume.SetMapper(volumeMapper)

volumeProperty = vtk.vtkVolumeProperty()

volumeProperty.SetInterpolationTypeToLinear()
volumeProperty.ShadeOn()
volumeProperty.SetAmbient(0.4)
volumeProperty.SetDiffuse(0.6)
volumeProperty.SetSpecular(0.2)

compositeOpacity = vtk.vtkPiecewiseFunction()
compositeOpacity.AddPoint(70,0.00)
compositeOpacity.AddPoint(90,0.40)
compositeOpacity.AddPoint(180,0.60)
volumeProperty.SetScalarOpacity(compositeOpacity)

volumeGradientOpacity = vtk.vtkPiecewiseFunction()
volumeGradientOpacity.AddPoint(10,0.00)
volumeGradientOpacity.AddPoint(90,0.50)
volumeGradientOpacity.AddPoint(100,1.0)
volumeProperty.SetGradientOpacity(volumeGradientOpacity)

color = vtk.vtkColorTransferFunction()
color.AddRGBPoint(0.000, 0.00, 0.00, 0.00)
color.AddRGBPoint(64.00, 1.00, 0.52, 0.30)
color.AddRGBPoint(190.0, 1.00, 1.00, 1.00)
color.AddRGBPoint(220.0, 0.20, 0.20, 0.20)
volumeProperty.SetColor(color)

volume.SetProperty(volumeProperty)

renderer = vtk.vtkRenderer()
renderer.AddVolume(volume)

renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(renderer)
renderWindowInteractor = vtk.vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)
style = vtk.vtkInteractorStyleTrackballCamera()
renderWindowInteractor.SetInteractorStyle(style)
renderWindowInteractor.Initialize()
renderer.ResetCamera()
renderWindow.Render()
renderWindowInteractor.Start()
