# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\AAA个人项目\ImageProcessSystem\Designer\ImageProcess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageProcess(object):
    def setupUi(self, ImageProcess):
        ImageProcess.setObjectName("ImageProcess")
        ImageProcess.resize(1500, 1107)
        self.centralwidget = QtWidgets.QWidget(ImageProcess)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 10, 1200, 1000))
        self.stackedWidget.setStyleSheet("border: 1px solid black;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(1230, 10, 51, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget.setFont(font)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.comboBox_method = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_method.setGeometry(QtCore.QRect(1340, 650, 141, 22))
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1250, 650, 91, 21))
        self.label.setObjectName("label")
        ImageProcess.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageProcess)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 23))
        self.menubar.setObjectName("menubar")
        ImageProcess.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageProcess)
        self.statusbar.setObjectName("statusbar")
        ImageProcess.setStatusBar(self.statusbar)

        self.retranslateUi(ImageProcess)
        self.stackedWidget.setCurrentIndex(1)
        self.listWidget.currentRowChanged['int'].connect(ImageProcess.On_ListWidget_currentrowchanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageProcess)

    def retranslateUi(self, ImageProcess):
        _translate = QtCore.QCoreApplication.translate
        ImageProcess.setWindowTitle(_translate("ImageProcess", "图像处理系统"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("ImageProcess", "静态"))
        item = self.listWidget.item(1)
        item.setText(_translate("ImageProcess", "三维"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.comboBox_method.setCurrentText(_translate("ImageProcess", "OpenCV"))
        self.comboBox_method.setItemText(0, _translate("ImageProcess", "OpenCV"))
        self.comboBox_method.setItemText(1, _translate("ImageProcess", "Torch"))
        self.comboBox_method.setItemText(2, _translate("ImageProcess", "Cuda"))
        self.comboBox_method.setItemText(3, _translate("ImageProcess", "OpenMp"))
        self.label.setText(_translate("ImageProcess", "选择处理方式："))
