# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\AAA个人项目\ImageProcessSystem\Designer\Static_Process.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Static_Process(object):
    def setupUi(self, Static_Process):
        Static_Process.setObjectName("Static_Process")
        Static_Process.resize(1200, 1000)
        self.Slider_bright = QtWidgets.QSlider(Static_Process)
        self.Slider_bright.setGeometry(QtCore.QRect(1010, 430, 111, 22))
        self.Slider_bright.setMinimum(-99)
        self.Slider_bright.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_bright.setObjectName("Slider_bright")
        self.label_4 = QtWidgets.QLabel(Static_Process)
        self.label_4.setGeometry(QtCore.QRect(950, 430, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Static_Process)
        self.label_5.setGeometry(QtCore.QRect(950, 460, 51, 16))
        self.label_5.setObjectName("label_5")
        self.Slider_contrast = QtWidgets.QSlider(Static_Process)
        self.Slider_contrast.setGeometry(QtCore.QRect(1010, 460, 111, 22))
        self.Slider_contrast.setMinimum(0)
        self.Slider_contrast.setMaximum(30)
        self.Slider_contrast.setProperty("value", 10)
        self.Slider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_contrast.setObjectName("Slider_contrast")
        self.pic_label = QtWidgets.QLabel(Static_Process)
        self.pic_label.setGeometry(QtCore.QRect(30, 10, 900, 900))
        self.pic_label.setStyleSheet("border: 1px solid black;")
        self.pic_label.setText("")
        self.pic_label.setObjectName("pic_label")
        self.groupBox = QtWidgets.QGroupBox(Static_Process)
        self.groupBox.setGeometry(QtCore.QRect(1080, 10, 111, 401))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Btn_rotate = QtWidgets.QPushButton(self.groupBox)
        self.Btn_rotate.setGeometry(QtCore.QRect(10, 220, 75, 23))
        self.Btn_rotate.setObjectName("Btn_rotate")
        self.Btn_Gaussian_Filter = QtWidgets.QPushButton(self.groupBox)
        self.Btn_Gaussian_Filter.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.Btn_Gaussian_Filter.setObjectName("Btn_Gaussian_Filter")
        self.btn_redo = QtWidgets.QPushButton(self.groupBox)
        self.btn_redo.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.btn_redo.setObjectName("btn_redo")
        self.Btn_change_size = QtWidgets.QPushButton(self.groupBox)
        self.Btn_change_size.setGeometry(QtCore.QRect(10, 190, 75, 23))
        self.Btn_change_size.setObjectName("Btn_change_size")
        self.Btn_undo = QtWidgets.QPushButton(self.groupBox)
        self.Btn_undo.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.Btn_undo.setObjectName("Btn_undo")
        self.Btn_erode = QtWidgets.QPushButton(self.groupBox)
        self.Btn_erode.setGeometry(QtCore.QRect(10, 280, 75, 23))
        self.Btn_erode.setObjectName("Btn_erode")
        self.Btn_MeanFilte = QtWidgets.QPushButton(self.groupBox)
        self.Btn_MeanFilte.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.Btn_MeanFilte.setObjectName("Btn_MeanFilte")
        self.Btn_invertcolor = QtWidgets.QPushButton(self.groupBox)
        self.Btn_invertcolor.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.Btn_invertcolor.setObjectName("Btn_invertcolor")
        self.Btn_dilate = QtWidgets.QPushButton(self.groupBox)
        self.Btn_dilate.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.Btn_dilate.setObjectName("Btn_dilate")
        self.Btn_select_pic = QtWidgets.QPushButton(self.groupBox)
        self.Btn_select_pic.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.Btn_select_pic.setObjectName("Btn_select_pic")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Static_Process)
        self.label_2.setGeometry(QtCore.QRect(950, 510, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_rgb = QtWidgets.QLineEdit(Static_Process)
        self.lineEdit_rgb.setGeometry(QtCore.QRect(1020, 540, 141, 20))
        self.lineEdit_rgb.setObjectName("lineEdit_rgb")
        self.lineEdit_xy = QtWidgets.QLineEdit(Static_Process)
        self.lineEdit_xy.setGeometry(QtCore.QRect(1020, 510, 141, 20))
        self.lineEdit_xy.setObjectName("lineEdit_xy")
        self.label_3 = QtWidgets.QLabel(Static_Process)
        self.label_3.setGeometry(QtCore.QRect(950, 540, 61, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Static_Process)
        self.Btn_MeanFilte.clicked.connect(Static_Process.On_Btn_Mean_Filter_clicked) # type: ignore
        self.Btn_Gaussian_Filter.clicked.connect(Static_Process.On_Btn_Gaussian_Filter_clicked) # type: ignore
        self.Btn_invertcolor.clicked.connect(Static_Process.On_Btn_invertcolor_clicked) # type: ignore
        self.Btn_undo.clicked.connect(Static_Process.On_Btn_undo_clicked) # type: ignore
        self.btn_redo.clicked.connect(Static_Process.On_Btn_redo_clicked) # type: ignore
        self.Btn_select_pic.clicked.connect(Static_Process.On_Btn_select_pic_clicked) # type: ignore
        self.Btn_change_size.clicked.connect(Static_Process.On_Btn_change_size_clicked) # type: ignore
        self.Btn_rotate.clicked.connect(Static_Process.On_Btn_rotate_clicked) # type: ignore
        self.Btn_dilate.clicked.connect(Static_Process.On_Btn_dilate_clicked) # type: ignore
        self.Btn_erode.clicked.connect(Static_Process.On_Btn_erode_clicked) # type: ignore
        self.Slider_bright.valueChanged['int'].connect(Static_Process.On_Slider_bright_changed) # type: ignore
        self.Slider_contrast.valueChanged['int'].connect(Static_Process.On_Slider_contrast_changed) # type: ignore
        self.pushButton.clicked.connect(Static_Process.vtk_render) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Static_Process)

    def retranslateUi(self, Static_Process):
        _translate = QtCore.QCoreApplication.translate
        Static_Process.setWindowTitle(_translate("Static_Process", "静态处理"))
        self.label_4.setText(_translate("Static_Process", "亮度："))
        self.label_5.setText(_translate("Static_Process", "对比度："))
        self.Btn_rotate.setText(_translate("Static_Process", "旋转"))
        self.Btn_Gaussian_Filter.setText(_translate("Static_Process", "高斯滤波"))
        self.btn_redo.setText(_translate("Static_Process", "还原"))
        self.Btn_change_size.setText(_translate("Static_Process", "缩放"))
        self.Btn_undo.setText(_translate("Static_Process", "撤销"))
        self.Btn_erode.setText(_translate("Static_Process", "腐蚀"))
        self.Btn_MeanFilte.setText(_translate("Static_Process", "均值滤波"))
        self.Btn_invertcolor.setText(_translate("Static_Process", "反色"))
        self.Btn_dilate.setText(_translate("Static_Process", "膨胀"))
        self.Btn_select_pic.setText(_translate("Static_Process", "打开图片"))
        self.pushButton.setText(_translate("Static_Process", "体渲染"))
        self.label_2.setText(_translate("Static_Process", "像素坐标："))
        self.label_3.setText(_translate("Static_Process", "像素颜色："))
