# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\AAA个人项目\ImageProcessSystem\Designer\Three_Dimension.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Three_Dimension(object):
    def setupUi(self, Three_Dimension):
        Three_Dimension.setObjectName("Three_Dimension")
        Three_Dimension.resize(1200, 1000)
        self.pic_label = QtWidgets.QLabel(Three_Dimension)
        self.pic_label.setGeometry(QtCore.QRect(30, 10, 900, 900))
        self.pic_label.setStyleSheet("border: 1px solid black;")
        self.pic_label.setText("")
        self.pic_label.setObjectName("pic_label")
        self.Btn_Volume = QtWidgets.QPushButton(Three_Dimension)
        self.Btn_Volume.setGeometry(QtCore.QRect(1000, 90, 75, 23))
        self.Btn_Volume.setObjectName("Btn_Volume")

        self.retranslateUi(Three_Dimension)
        self.Btn_Volume.clicked.connect(Three_Dimension.On_Btn_Volume_Clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Three_Dimension)

    def retranslateUi(self, Three_Dimension):
        _translate = QtCore.QCoreApplication.translate
        Three_Dimension.setWindowTitle(_translate("Three_Dimension", "Form"))
        self.Btn_Volume.setText(_translate("Three_Dimension", "体渲染"))
